- name: datatypes
  hosts: local
  connection: local
  vars:
   COURSE: AWSDEVOPS #string
   DURATION: 120 #number
   topics: #we have various topics so list is created
   - linux
   - shell
   - ansible
   - terraform
   - aws
   - K8
   live: true #boolean
   tools:
   ci: jenkins
   cm: ansible
   cloud: aws
   aws:
   - IAM
   - EC2
  tasks: 
  - name: here is the course details
    ansible.builtin.debug:
     msg: "HI, i am learning {{COURSE}} of duration {{DURATION}} and topics covered are {{topics}}, tools used are {{ tools }} and it is live from {{live}}."

    