- name: loops
  hosts: local
  connection: local
  tasks: 
  - name: print names
    ansible.builtin.debug:
     msg: " {{item}} "  #item is reserved keyword to loop the elements
    loop:
    - vishnu
    - janu 