- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: enter course name
    private: false #it is not confidential will appear on screen
  - name: DURATION
    prompt: enter duration 
    private: false
  tasks: 
  - name: enter course info
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}} and duration is {{DURATION}}"